const scenariosConfig = (urlBase) => {
  console.log('> A url pros prints é:', urlBase);
  return [
    {
      label: 'Home',
      pageInitial: urlBase,
      targetElementToWait: '.question-title',
      fullPage: true,
    },
    {
      label: 'Menu - Para seu Negocio',
      url: urlBase + '/',
      targetElementToWait: 'header#menu',
      breakPointFullpage: ['phone'],
      pageScript: '../scripts/scenario/expand-menu-items.js',
      customSelectors: {
        firstLevelItem: 'header#menu nav > ul:nth-child(1) > li:nth-child(1)',
        secondLevelItem:
          'header#menu nav > ul:nth-child(1) > li:nth-child(1) ul li:nth-child(1)',
        mobileMenuToggle: '.menu-toggle__open',
      },
    },
    {
      label: 'Footer - Pagbank',
      url: urlBase + '/ligue-central-vendas',
      targetElementToWait: 'footer',
      target: 'footer',
      pageScript: '../scripts/scenario/expand-footer-items.js',
      customSelectors: {
        footerItem: '.footer__grid:nth-child(2) ul > li:first-child',
      },
    },
    {
      label: 'Resultados de Busca',
      url: urlBase + '/buscar?q=como+ativar',
      targetElementToWait: '#container-questions',
      fullPage: true,
    },
    {
      label: 'Resultados de Busca Autocomplete',
      url: urlBase + '/buscar/autocompleter?q=moderninha',
      targetElementToWait: '#container-questions',
      fullPage: true,
    },
    {
      label: 'Resultados de Busca Não Encontrado',
      url: urlBase + '/buscar?q=q24q4terewq42q235',
      targetElementToWait: '.content--categoria.empty',
      fullPage: true,
    },
    {
      label: 'Página de Erro',
      url:
        urlBase +
        '/duvida/preciso-ser-pessoa-juridica-para-vender-com-a-moderninha/18128',
      targetElementToWait: 'section#page-app-down',
      fullPage: true,
    },
    {
      label: 'Artigo - Categoria',
      url: urlBase + '/aplicativo-pagbank/57',
      targetElementToWait: 'section.content--categoria',
      fullPage: true,
    },
    {
      label: 'Artigo - SubCategoria',
      url: urlBase + '/aplicativo-pagbank/57/como-usar/512',
      targetElementToWait: 'section.content--subcategoria',
      fullPage: true,
    },
    {
      label: 'Artigo - Conteudo',
      url: urlBase + '/duvida/o-que-e-o-aplicativo-pagbank/379',
      targetElementToWait: 'span.rate-yes',
      fullPage: true,
    },
    {
      label: 'Artigo - Banner',
      url:
        urlBase +
        '/duvida/como-eu-faco-para-vender-minha-maquina-do-pagseguro/461',
      targetElementToWait: 'span.rate-yes',
      fullPage: true,
    },
    {
      label: 'Central de Vendas',
      url: urlBase + '/ligue-central-vendas',
      targetElementToWait: '.central-vendas__title',
      fullPage: true,
    },
    {
      label: 'Central Atendimento',
      url: urlBase + '/ligue-central-atendimento',
      targetElementToWait: '.central-atendimento__content',
      fullPage: true,
    },
    {
      label: 'Menu de Categorias',
      url: urlBase + '/ligue-central-atendimento',
      pageScript: '../scripts/scenario/expand-category-items.js',
      targetElementToWait: '.central-atendimento__content',
      target: '.content__menu',
      customSelectors: {
        header: '.header',
        search: '#search-banner',
        cat01:
          '#accordion-0 > div > ul > li > div > div > ol > li > ul > li:nth-child(1)',
        cat02:
          '#accordion-0 > div > ul > li > div > div > ol > li > ul > li:nth-child(2)',
        cat03:
          '#accordion-0 > div > ul > li > div > div > ol > li > ul > li:nth-child(3)',
        cat04:
          '#accordion-0 > div > ul > li > div > div > ol > li > ul > li:nth-child(4)',
        cat05:
          '#accordion-0 > div > ul > li > div > div > ol > li > ul > li:nth-child(5)',
        businesshowMore: 'a#question-see-more-link-0',
      },
    },
    {
      label: 'Menu Acesso Rápido das Categorias - Sem Acento',
      url: urlBase + '/ligue-central-atendimento',
      targetElementToWait: '.central-atendimento__content',
      pageScript: '../scripts/scenario/quick-menu.js',
      fullPage: true,
      customSelectors: {
        header: '.header',
        search: '#search-banner',
        quickAcess: '#search-quick-access',
      },
    },
    {
      label: 'Menu Acesso Rápido das Categorias - Com Acento',
      url: urlBase + '/ligue-central-atendimento',
      targetElementToWait: '.central-atendimento__content',
      pageScript: '../scripts/scenario/quick-menu.js',
      fullPage: true,
      customSelectors: {
        header: '.header',
        search: '#search-banner',
        quickAcess: '#search-quick-access',
        scented: true,
      },
    },
    {
      label: 'Logado - Enviar e-mail',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        dropdownItem: '.dropdown-filter__item',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        textarea: 'textarea#enviar-email-description',
        sendMailButton: '#enviar-email p a',
        sendMailFeedback: '.textarea-alert-container .alert.alert-success',
      },
    },
    {
      label: 'Logado - Enviar e-mail - Confirmação',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        dropdownItem: '.dropdown-filter__item',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        textarea: 'textarea#enviar-email-description',
        sendMailButton: '#enviar-email p a',
        sendMailFeedback: '.textarea-alert-container .alert.alert-success',
      },
      customVariables: {
        flow: 'success',
      },
    },
    {
      label: 'Logado - Enviar e-mail - Erro Validação',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        dropdownItem: '.dropdown-filter__item',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        textarea: 'textarea#enviar-email-description',
        sendMailButton: '#enviar-email p a',
        sendMailFeedback: '.textarea-alert-container .alert.alert-success',
        sendMailAlert: '.enviar-email-messages .alert.alert-danger',
      },
      customVariables: {
        flow: 'validation-error',
      },
    },
    {
      label: 'Logado - Enviar e-mail - Warning Validação',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        dropdownItem: '.dropdown-filter__item',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        textarea: 'textarea#enviar-email-description',
        sendMailButton: '#enviar-email p a',
        sendMailFeedback: '.textarea-alert-container .alert.alert-success',
        sendMailAlert: '.enviar-email-messages .alert.alert-warning',
      },
      customVariables: {
        flow: 'validation-warning',
      },
    },
    {
      label: 'Logado - Enviar e-mail - LGPD - Anonimização',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado-lgpd.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        textarea: 'textarea#enviar-email-description',
        dropdownItem:
          '.dropdown-filter__item[data-value="823fa983-04f4-44ff-8c74-453c16a5df11"]',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        sendMailButton: '#enviar-email p a',
        sendMailFeedbackSuccess:
          '.textarea-alert-container .alert.alert-success',
        sendMailFeedbackWait: '.textarea-alert-container .alert.alert-wait',
      },
      customVariables: {
        flow: 'lgpd-anonymization',
      },
    },
    {
      label: 'Logado - Enviar e-mail - LGPD - Compartilhamento',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado-lgpd.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        textarea: 'textarea#enviar-email-description',
        dropdownItem:
          '.dropdown-filter__item[data-value="0b28fd9a-fb81-4168-8b0a-c4eb553dfc86"]',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        sendMailButton: '#enviar-email p a',
        sendMailFeedbackSuccess:
          '.textarea-alert-container .alert.alert-success',
        sendMailFeedbackWait: '.textarea-alert-container .alert.alert-wait',
      },
      customVariables: {
        flow: 'lgpd-sharing',
      },
    },
    {
      label: 'Logado - Enviar e-mail - LGPD - Eliminação',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado-lgpd.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        textarea: 'textarea#enviar-email-description',
        dropdownItem:
          '.dropdown-filter__item[data-value="76e6893f-10d9-4847-8e03-58bb9dccd719"]',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        sendMailButton: '#enviar-email p a',
        sendMailFeedbackSuccess:
          '.textarea-alert-container .alert.alert-success',
        sendMailFeedbackWait: '.textarea-alert-container .alert.alert-wait',
      },
      customVariables: {
        flow: 'lgpd-deletion',
      },
    },
    {
      label: 'Logado - Enviar e-mail - LGPD - Esquecimento',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado-lgpd.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        textarea: 'textarea#enviar-email-description',
        dropdownItem:
          '.dropdown-filter__item[data-value="cc6adef9-815b-453d-9e25-18e008da02ff"]',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        sendMailButton: '#enviar-email p a',
        sendMailFeedbackSuccess:
          '.textarea-alert-container .alert.alert-success',
        sendMailFeedbackWait: '.textarea-alert-container .alert.alert-wait',
      },
      customVariables: {
        flow: 'lgpd-forgot',
      },
    },
    {
      label: 'Logado - Enviar e-mail - LGPD - Levantamento',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado-lgpd.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        textarea: 'textarea#enviar-email-description',
        dropdownItem:
          '.dropdown-filter__item[data-value="f3179a46-1452-438b-91c4-c2432396cd52"]',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        sendMailButton: '#enviar-email p a',
        sendMailFeedbackSuccess:
          '.textarea-alert-container .alert.alert-success',
        sendMailFeedbackWait: '.textarea-alert-container .alert.alert-wait',
      },
      customVariables: {
        flow: 'lgpd-gathering',
      },
    },
    {
      label: 'Logado - Enviar e-mail - LGPD - Outros',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado-lgpd.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        textarea: 'textarea#enviar-email-description',
        dropdownItem:
          '.dropdown-filter__item[data-value="98535e8b-8341-42d4-8ca9-8396ee91798b"]',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        sendMailButton: '#enviar-email p a',
        sendMailFeedbackSuccess:
          '.textarea-alert-container .alert.alert-success',
        sendMailFeedbackWait: '.textarea-alert-container .alert.alert-wait',
      },
      customVariables: {
        flow: 'lgpd-others',
      },
    },
    {
      label: 'Logado - Enviar e-mail - LGPD - Portabilidade',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado-lgpd.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        textarea: 'textarea#enviar-email-description',
        dropdownItem:
          '.dropdown-filter__item[data-value="1b2f1817-0e96-4d72-96f2-53b2672ae87b"]',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        sendMailButton: '#enviar-email p a',
        sendMailFeedbackSuccess:
          '.textarea-alert-container .alert.alert-success',
        sendMailFeedbackWait: '.textarea-alert-container .alert.alert-wait',
      },
      customVariables: {
        flow: 'lgpd-portability',
      },
    },
    {
      label: 'Logado - Enviar e-mail - Anexo de imagens',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        dropdownItem: '.dropdown-filter__item',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        textarea: 'textarea#enviar-email-description',
        sendMailButton: '#enviar-email p a',
        sendMailFeedback: '.textarea-alert-container .alert.alert-success',
        sendMailAlert: '.enviar-email-messages .alert.alert-warning',
        attachmentInput: '.form-field-attachment__actions > input',
        attachmentItem: 'ul.form-field-attachment__list li.attachment-item',
      },
      customVariables: {
        flow: 'attachment',
        attachmentType: 'image',
      },
    },
    {
      label: 'Logado - Enviar e-mail - Anexo de Doc',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        dropdownItem: '.dropdown-filter__item',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        textarea: 'textarea#enviar-email-description',
        sendMailButton: '#enviar-email p a',
        sendMailFeedback: '.textarea-alert-container .alert.alert-success',
        sendMailAlert: '.enviar-email-messages .alert.alert-warning',
        attachmentInput: '.form-field-attachment__actions > input',
        attachmentItem: 'ul.form-field-attachment__list li.attachment-item',
      },
      customVariables: {
        flow: 'attachment',
        attachmentType: 'document',
      },
    },
    {
      label: 'Logado - Enviar e-mail - Anexo Erros',
      pageInitial: urlBase + '/',
      targetLoggedUrl: urlBase + '/email-central-atendimento',
      pageScript: '../scripts/scenario/enviar-email-logado.js',
      login: true,
      fullPage: true,
      customSelectors: {
        inputUsername: 'input#user',
        inputPassword: 'input#password',
        btnEntrar: 'button._2IHsK._1osDF._1-tGF',
        targetElementToWait: 'h1.enviar-email__title',
        dropdown: '.dropdown-filter__select',
        dropdownItem: '.dropdown-filter__item',
        stillHaveDoubtsButton: 'a#button-doubts',
        sendMailContainer: '#enviar-email',
        textarea: 'textarea#enviar-email-description',
        sendMailButton: '#enviar-email p a',
        sendMailFeedback: '.textarea-alert-container .alert.alert-success',
        sendMailAlert: '.enviar-email-messages .alert.alert-warning',
        attachmentInput: '.form-field-attachment__actions > input',
        attachmentItem: 'ul.form-field-attachment__list li.attachment-item',
      },
      customVariables: {
        flow: 'attachment',
        attachmentType: 'unknown',
      },
    },
  ];
};

module.exports = {
  scenariosConfig,
};
